# Generated by Django 2.2.9 on 2024-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfpb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Joinha',
            },
        ),
    ]
